### ISSUE TITLE
Replace str.format() and string concatenation in samples with f-string

### ISSUE THREAD

**Issue by parthea** [googleapis/python-retail#164]
In PR https://github.com/googleapis/python-retail/pull/160, there is a review comment requesting to replace all str.format() or string concatenation in samples with an f-string. I'm going to track this as a separate work item because it affects all retail samples. See https://github.com/googleapis/python-retail/pull/160#discussion_r812097695

**Comment by parthea** [comment]
@tetiana-karasova Please could you take a look?

**Comment by t-karasova** [comment]
I will fix this
