### ISSUE TITLE
Unable to create instance of `ProductDetail` with quantity

### ISSUE THREAD

**Issue by HenrikOssipoff** [googleapis/python-retail#36]
I'm a tiny bit unsure whether or not this is us using the library incorrectly, if it's a protobuf thing, or whether or not there's some issue with the library. We're leaning towards it being an issue with one of the latter two, so we're leaving this issue here -- very sorry in advance, if it's on our end.

#### Environment details

  - OS type and version: Mac OS 11.3.1
  - Python version: 3.9.0
  - pip version: 21.1.1
  - `google-cloud-retail` version: 0.1.0

#### Steps to reproduce

  1. Attempt to create an instance of `ProductDetail` with a quantity set
  2. An exception is thrown, seemingly because it can't convert the quantity into an Int32Value object

#### Code example

```python
from google.cloud.retail_v2 import ProductDetail
ProductDetail(quantity=1)
```

#### Stack trace
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/proto/message.py", line 506, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File "/usr/local/lib/python3.9/site-packages/proto/marshal/marshal.py", line 208, in to_proto
    pb_value = rule.to_proto(value)
  File "/usr/local/lib/python3.9/site-packages/proto/marshal/rules/wrappers.py", line 38, in to_proto
    return self._proto_type(value=value)
ValueError: Protocol message Int32Value has no "value" field.
```

**Comment by danoscarmike** [comment]
@HenrikOssipoff thanks for reaching out.

I'm not familiar with this API but according to the library docs, [`ProductDetail`](https://googleapis.dev/python/retail/latest/retail_v2/types.html#google.cloud.retail_v2.types.ProductDetail) has a required `product` field.

Can you give something like this a try?
```python
from google.cloud.retail_v2 import Product, ProductDetail
ProductDetail(product=Product(), quantity=1)
```

**Comment by parthea** [comment]
Hi @HenrikOssipoff,

I'm going to mark this issue as resolved but please feel free to re-open it if you have additional questions.
